### ISSUE TITLE
Pvector and python incompatibilities.

### ISSUE THREAD

**Issue by jeacom25b** [Dogeek/pyprocessing#12]
I was trying to get The new implementation of PVector to work but it has quite a few bugs.

 I believe that there's a fundamental difference about python that makes implementing a processing compatible PYVector very involved.

* Python doesnt have function overloads.

For example In Processing, calling PVector.add(v1, v2) will return a new PVector but calling v1.add(v2) will assign the sum of v1 and v2 to the v1 instance.

It would be very involved to reproduce it in python using a single class. And indeed, the current implementation of add dont work.
Having it as a class method dont cut it because instances won't ever be passed to this function.

probably a better approach would be to have a singleton instance of a class called PVector which encapsulates the behavior of the PVector class in Processing and have a \_\_call__ method which instantiate a new vector out of another class, maybe called PYVector or something, and this other class would be the actual implementation for the vector per se.

That way we could more easily define the behavior of PVector I believe.

Edit:
I dont have much of any experience with Processing so please correct if I'm wrong.

**Comment by sbordeyne** [comment]
There's definitely a way to do it. It's just that the add method needs to return a PVector instead of None.

Python has also various ways of mimicking overloading, namely tuple unpacking and through decorators

**Comment by jeacom25b** [comment]
The thing is that the add method is a bound method while in an instance of the class but is a normal function while in the type itself, so it can get messy pretty fast, `@classmethod` technically prevents this but also prevents it from ever accessing the instance "self", which is replaced with the class itself "cls".

I saw [this line][1] and it exemplifies what I mean: `cls.x += x`, this definitely won't work as `cls.x` is not defined, it's trying to change the PVector type itself and not the instance.

[1]: https://github.com/Dogeek/pyprocessing/blob/a04941ea7a69d533e6bbb333b15e0925f5dbe425/pyprocessing/math.py#L39

**Comment by sbordeyne** [comment]
One workaround I can think of, off the top of my head :

- make the add/sub/mult/div methods staticmethods instead, that only handle the case for `PVector.add(vector1, vector2)` (and similarly)
- define the instance specific adding/substracting etc in the `__add__`, `___sub__` methods only

I don't quite like this approach though as it's quite far from processing, and would be way off the 'copy/paste processing code' philosophy.

I'll think about it some more to find a proper solution. After all, there has to be a way to make it work (a decorator should be able to handle it, though it might get messy)

**Comment by jeacom25b** [comment]
I guess there are two options.

Either complicate things on the converter, or complicate things on the PVector impl.
edit:
I've been prototyping a [Implementation for PVector][1] also, It probably is nowhere close to the actual behavior of Processing but it sems to work.

[1]: https://repl.it/@jeacom25b/Pvector-Prototype#main.py

**Comment by sbordeyne** [comment]
The best way to go is to complicate things on the PVector API. 

I indeed made an automated converter tool, but it's only a tool to convert existing processing sketches. We also have to take into account developers that will use PyProcessing straight away, thus having a common interface between Processing and PyProcessing is the most important part of this library

**Comment by jeacom25b** [comment]
I believe having to learn to use += instead of .add is less of a concern, probably developers will learn it just fine, just pack some examples showing how its used, they would have to learn python anyway and if they alredy know, probably they also know that operator overloads are the default way to go as every single python lib out there uses them.

**Comment by sbordeyne** [comment]
It goes against the philosophy of the project though (which is to be as close to processing as possible), while adding all of the python goodness (operator overloading will be a thing obviously, but only on top of the .add method, as an added bonus)

Also, processing is used by a lot of non-devs (like artists, or scientists wanting to make simulations), and pyprocessing is also for them, since processing itself doesn't offer anywhere close to the amount of libraries python has.

**Comment by jeacom25b** [comment]
In that case, probably is best to keep PVector separated in two classes, one which handles the cases of static calls and other to handle the case of instances, so we would have two distinct implementations for each function.

eg
```python
class PVector:
    def __call__(x, y, z):
        return PVectorImpl(x, y, z)

    def add(a, b, target=None):
       ...

class PVectorImpl:
    ...
    def add(a, b, target=None):
        ...
```

but I think it could cause lots of unexpected behavior for people more used to python, for example isinstance() woudn't work properly unless you know the difference between both classes.

**Comment by sbordeyne** [comment]
you can overload `__instancecheck__` to make `isinstance()` work though.

I don't quite understand how making a callable would solve the issue though

**Comment by jeacom25b** [comment]
The idea was that the PVector class would not actually be a type, rather it would be an singleton that would behave line a type, so when you call it instead of \_\_init__ it would be \_\_call__ so it can return any other object instead of a instance of itself, the object it would return in that case would be the actual implementation for the Vector, that way each could have its own implementation of those functions that behave differently depending on whether we are calling from an instance.

edit:
just thought that its also possible to have \_\_getattribute__ be defined and have it override which function is being called, so we could theoretically have two implementations on the same class, since \_\_getattribute__ only runs when its on an instance and not on the type itself, it could also be used to control which implementations of .add/sub/etc we are using.

**Comment by mohd874** [comment]
Hello all,

I was following the project and found this problem interesting. I did my research and found libraries that do method overloading, but none worked for this case. I came up with the solution below based on the discussion here. Hope it can help.

```python
# This should be hidden from the user
class _PVector(object):
    def __call__(self, x, y):
        p = PVectorImpl()
        p.x = x
        p.y = y
        return p

    @classmethod
    def add(cls, target, other):
        print('class method')
        result = PVector(target.x+other.x, target.y + other.y)

        return result

    def __repr__(self):
        return f'PVector({self.x}, {self.y})'

# Actual implementation of PVector 
class PVectorImpl(_PVector):
    def add(self, other):
        print('method')
        self.x += other.x
        self.y += other.y

# The PVector var will be exposed to the user
PVector = _PVector()

# The __call__ will act as a proxy __init__ which will return PVectorImpl
p1 = PVector(1,2)
p2 = PVector(10,10)

# This will call the instance method
p1.add(p2)
print(f'p1.add(p2) => {p1}')

# This will call the class method
p3 = PVector.add(p1, p2)
print(f'PVector.add(p1, p2) => {p3}')
```

**Comment by jeacom25b** [comment]
@mohd874 thats exactly how I imagined it

I also found another workaround using metaclasses.

```python
class PVectorMeta(type):

    def __getattr__(self, attr):
        if attr == 'add':
            return self._class_add

        raise AttributeError(attr)

    @staticmethod
    def _class_add(a, b, target=None):
        print('class add called')


class PVector(metaclass=PVectorMeta):

    def __getattr__(self, attr):
        if attr == 'add':
            return self._instance_add

        raise AttributeError(attr)

    def _instance_add(self, other, target=None):
        print('instance add called')

print(PVector.add(None, None)) # class add called
print(PVector().add(None, None)) # instance add called

```

**Comment by sbordeyne** [comment]
Thanks @jeacom25b that's exactly the workaround I was looking for. I'm going to push the changes now

**Comment by mohd874** [comment]
I don't know much about metaclass, can you explain to me how it is better that than proxy solution? I am just curious 😊.

**Comment by sbordeyne** [comment]
The proxy solution is inelegant, because you're not making a class, you're making a callable. As far as design patterns go, this would be a Factory pattern, fyi. It introduces several quirks that I was not happy with, namely instance checks, as well as importing an instance when using a PVector.

With the metaclass, it's much more contained, you're importing a class (which makes more sense) and you can instance check regularly. On top of that, developers can make classes that inherit from the PVector class to add their own vector-related math on top of it.

**Comment by mohd874** [comment]
Thank you for the explanation.
