### ISSUE TITLE
fill() and stroke() don't do anything inside draw()

### ISSUE THREAD

**Issue by PeanutbutterWarrior** [Dogeek/pyprocessing#18]
When either `fill()` or `stroke()` are run from inside draw, they do not change the colors at all. They work as intended inside `setup()`.

Below is an example:

    from pyprocessing import (
        size, stroke, frame_rate, fill,
        background, square,
    )
    
    def setup():
        size(640, 360)
        stroke(0)
        fill(255)
        frame_rate(60)
        background(50)
    
    def draw():
        square(10, 10, 50)  # Draws white box as expected
        fill(127)
        square(70, 10, 50)  # Should draw grey box, instead draws white box

**Comment by jeacom25b** [comment]
Some attributes in window.Window seems to not be updating while draw() is running, only when its initialized it seems.

I made a spaghetti fix, no idea of how it was supposed to be but seems to work.

```diff
diff --git a/pyprocessing/renderer/tkinter/window.py b/pyprocessing/renderer/tkinter/window.py
index e8871b4..bcb8ec2 100644
--- a/pyprocessing/renderer/tkinter/window.py
+++ b/pyprocessing/renderer/tkinter/window.py
@@ -13,9 +13,6 @@ class Window(tk.Frame):
 
         width = namespace.get('width', 640)
         height = namespace.get('height', 480)
-        self.frame_rate = namespace.get('framerate', 60)
-        self.stroke = namespace.get('stroke', '#000000')
-        self.fill = namespace.get('fill', '#ffffff')
 
         self.canvas = tk.Canvas(self, width=width, height=height)
         self.canvas.pack(fill=tk.BOTH, expand=True)
@@ -23,13 +20,22 @@ class Window(tk.Frame):
         self.queued_actions = deque()
         self.canvas_objs = []
 
+    @property
+    def frame_rate(self):
+        return self.pyprocessing.namespace.get('framerate', 60)
+
+    @property
+    def stroke(self):
+        return self.pyprocessing.namespace.get('stroke', '#000000')
+
+    @property
+    def fill(self):
+        return self.pyprocessing.namespace.get('fill', '#ffffff')
+
     def setup(self):
         namespace = self.pyprocessing.namespace
         width = namespace.get('width', 640)
         height = namespace.get('height', 480)
-        self.frame_rate = namespace.get('framerate', 60)
-        self.stroke = namespace.get('stroke', '#000000')
-        self.fill = namespace.get('fill', '#ffffff')
 
         self.config(width=width, height=height)
         self.canvas.config(width=width, height=height)

```

**Comment by sbordeyne** [comment]
Using properties is a good idea. I may refactor that to move those onto the `TkRenderer` object.

There is also some optimisation that can be done, as accessing a dictionary is quite slow. 

I'll probably make the optimisation at the PyProcessing.namespace object level though, by caching the values (until they change)
