### ISSUE TITLE
AttributeError: 'super' object has no attribute '__getattr__'

### ISSUE THREAD

**Issue by COLOR-SKY** [Dogeek/pyprocessing#24]
I attempted to run the example code. Got this error.
<img width="961" alt="WX20201223-212808@2x" src="https://user-images.githubusercontent.com/21962518/103000359-e0c5b980-4565-11eb-8a24-3594fa56e848.png">

Any help?

**Comment by sbordeyne** [comment]
Thanks for the report, I'll look into that ASAP. I haven't worked on this library for a few months though so it may take a bit of time.

**Comment by COLOR-SKY** [comment]
> Thanks for the report, I'll look into that ASAP. I haven't worked on this library for a few months though so it may take a bit of time.

Thanks for the speedy reply. Notice that return None upon the AttributeError can result in a chain of other problems. Excellent work by the way.

**Comment by sbordeyne** [comment]
This is fixed in a7df329f07600fe532847794c9246a340983468e

**Comment by COLOR-SKY** [comment]
> This is fixed in [a7df329](https://github.com/Dogeek/pyprocessing/commit/a7df329f07600fe532847794c9246a340983468e)

Splendid!
