### ISSUE TITLE
`pip install pyprocessing` does not work

### ISSUE THREAD

**Issue by minhduc0711** [Dogeek/pyprocessing#4]
Seems like it's installing another version https://pypi.org/project/pyprocessing/

**Comment by sbordeyne** [comment]
Damn, I didn't think to check for existing python packages with that name.

Also, I am holding off a little on uploading the package to PyPI. The first release should be usable as it, with at least most of the functions and objects to work with 2D Graphics.

**Comment by sbordeyne** [comment]
I made the first release on PyPI, and adjusted the README with the correct PyPI package name.
